import { Router } from "express";
import UserController from "./app/Controllers/UserController.js";
import SessionController from "./app/Controllers/SessionController.js";
import ProductController from "./app/Controllers/ProductController.js";
import CategoryController from "./app/Controllers/CategoryController.js";
import CheckoutController from "./app/Controllers/CheckoutController.js";
import OrderController from "./app/Controllers/OrderController.js";
import AddressController from "./app/Controllers/AddressController.js";
import ShippingController from "./app/Controllers/ShippingController.js";
import StoreSettingController from "./app/Controllers/StoreSettingController.js";
import CouponController from "./app/Controllers/CouponController.js";
import multer from "multer";
import multerConfig from "./config/multer.cjs";
import authMiddleware from "./app/middlewares/auth.js";
import adminMiddleware from "./app/middlewares/admin.js";
import { authRateLimit, writeRateLimit } from "./app/middlewares/rateLimit.js";

const routes = new Router();
const uploud = multer(multerConfig);

routes.post("/users", authRateLimit, UserController.store);
routes.post("/session", authRateLimit, SessionController.store);

routes.get("/products", ProductController.index);
routes.get("/categories", CategoryController.index);
routes.get("/store/public-settings", StoreSettingController.showPublic);
routes.get("/melhor-envio/callback", StoreSettingController.handleMelhorEnvioCallback);
routes.get("/checkout/return", CheckoutController.handleCheckoutReturn);
routes.post("/mercado-pago/webhook", OrderController.handleMercadoPagoWebhook);
routes.post("/coupons/validate", writeRateLimit, CouponController.validate);

routes.use(authMiddleware);
routes.get("/me", UserController.show);
routes.put("/me", writeRateLimit, UserController.update);
routes.get("/me/orders", OrderController.indexMine);
routes.get("/me/addresses", AddressController.index);
routes.post("/me/addresses", writeRateLimit, AddressController.store);
routes.put("/me/addresses/:id", writeRateLimit, AddressController.update);
routes.delete("/me/addresses/:id", writeRateLimit, AddressController.destroy);
routes.post("/shipping/quotes", writeRateLimit, ShippingController.quote);
routes.post("/checkout/session", writeRateLimit, CheckoutController.createSession);
routes.post("/me/orders/:id/retry-payment", writeRateLimit, CheckoutController.retryPayment);
routes.post("/checkout/confirm", writeRateLimit, OrderController.confirmCheckout);
routes.get("/admin/users", adminMiddleware, UserController.indexAdmin);
routes.get("/admin/products", adminMiddleware, ProductController.indexAdmin);
routes.get("/admin/coupons", adminMiddleware, CouponController.indexAdmin);
routes.get("/admin/orders", adminMiddleware, OrderController.indexAdmin);
routes.put("/admin/orders/:id", adminMiddleware, writeRateLimit, OrderController.updateAdmin);
routes.post("/admin/orders/:id/melhor-envio/prepare", adminMiddleware, writeRateLimit, OrderController.prepareMelhorEnvioAdmin);
routes.post("/admin/orders/:id/melhor-envio/checkout", adminMiddleware, writeRateLimit, OrderController.checkoutMelhorEnvioAdmin);
routes.post("/admin/orders/:id/melhor-envio/generate", adminMiddleware, writeRateLimit, OrderController.generateMelhorEnvioAdmin);
routes.post("/admin/orders/:id/melhor-envio/print", adminMiddleware, writeRateLimit, OrderController.printMelhorEnvioAdmin);
routes.post("/admin/orders/:id/melhor-envio/sync", adminMiddleware, writeRateLimit, OrderController.syncMelhorEnvioAdmin);
routes.post("/admin/orders/:id/melhor-envio/reset", adminMiddleware, writeRateLimit, OrderController.resetMelhorEnvioAdmin);
routes.get("/admin/store-settings", adminMiddleware, StoreSettingController.show);
routes.get("/admin/store-settings/melhor-envio/test", adminMiddleware, StoreSettingController.testMelhorEnvio);
routes.get("/admin/store-settings/melhor-envio/connect-url", adminMiddleware, StoreSettingController.getMelhorEnvioAuthorizationUrl);
routes.post("/admin/store-settings/melhor-envio/disconnect", adminMiddleware, writeRateLimit, StoreSettingController.disconnectMelhorEnvio);
routes.put("/admin/store-settings", adminMiddleware, writeRateLimit, StoreSettingController.update);
routes.post("/products", adminMiddleware, writeRateLimit, uploud.array('files', 3), ProductController.store);
routes.put("/products/:id", adminMiddleware, writeRateLimit, uploud.array('files', 3), ProductController.update);
routes.delete("/products/:id", adminMiddleware, writeRateLimit, ProductController.destroy);
routes.post("/categories", adminMiddleware, writeRateLimit, uploud.single('file'), CategoryController.store);
routes.put("/categories/:id", adminMiddleware, writeRateLimit, uploud.single('file'), CategoryController.update);
routes.delete("/categories/:id", adminMiddleware, writeRateLimit, CategoryController.destroy);
routes.post("/admin/coupons", adminMiddleware, writeRateLimit, CouponController.storeAdmin);
routes.put("/admin/coupons/:id", adminMiddleware, writeRateLimit, CouponController.updateAdmin);
routes.delete("/admin/coupons/:id", adminMiddleware, writeRateLimit, CouponController.destroyAdmin);
routes.put("/admin/users/:id", adminMiddleware, writeRateLimit, UserController.updateAdmin);
routes.delete("/admin/users/:id", adminMiddleware, writeRateLimit, UserController.destroyAdmin);

export default routes;
